version: "3.1"
services:
  php-fpm:
    build: ./php/
    links:
      - mysql
      - redis
    volumes:
      - ../www:/www:rw
      - ./php/php-fpm.conf:/usr/local/etc/php/php-fpm.conf:ro
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ../logs/php-fpm:/var/log/php-fpm:rw
    ports:
      - "9000:9000"
    restart: always
    command: php-fpm
  nginx:
    build: ./nginx/
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ../www:/www:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ../logs/nginx:/var/log/nginx:rw
    ports:
      - "8080:8080"
      - "8000:8000"
    restart: always
    command: nginx -g 'daemon off;'
    
  mysql:
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql:rw
      - ../logs/mysql:/var/log/mysql:rw
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: docker_web
        MYSQL_USER: docker_web
        MYSQL_PASSWORD: docker_web
    restart: always
    command: "--character-set-server=utf8"

  redis:
    build: ./redis/
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always

